version: "3.8"

services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    environment:
      - WG_HOST=10.0.0.1/16
      - PASSWORD_HASH=$$2a$$12$$FnJqGCK9FB9w9xGVU/iTDO8/991dwiKv1u6U6.AZRmScNnkPoohAy
      - WG_DEFAULT_DNS=10.20.10.1         # DNS asignado a los clientes VPN
      - WG_DEFAULT_ADDRESS=10.8.0.10
    volumes:
      - /home/pi/docker/wgeasy:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
#    networks:
#      wg-easy_wg-easy:
#        ipv4_address: 10.8.1.2

#networks:
#  wg-easy_wg-easy:
#    external: true